 CREATE TABLE "MADANG"."MEMBERLIST" 
   (	"USERID" VARCHAR2(40 BYTE), 
	"USERPWD" VARCHAR2(40 BYTE)
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "MADANG" ;
REM INSERTING into MADANG.MEMBERLIST
SET DEFINE OFF;
Insert into MADANG.MEMBERLIST (USERID,USERPWD) values ('admin','admin');
Insert into MADANG.MEMBERLIST (USERID,USERPWD) values ('shin','shin');
